### ISSUE TITLE
Error running example data file

### ISSUE THREAD

**Issue by sohamdange31** [BatParDeveloperTeam/BatPar#1]
Hi, I tried running the example GITT data file by following steps in the developer manual. I am getting following error - 

```
Index exceeds the number of array elements. Index must not exceed 2.

Error in datasplitter (line 15)
               S_pesudobound = S_j(ii) - (S_j(ii+2) - S_j(ii+1))/OPT_factor;

Error in ECM_Easy (line 119)
[data, S_j] = datasplitter(t,I,V,T,S,S_j,bounds,flags); % sort out experimental data as SOC dependent

Error in run (line 112)
evalin('caller', strcat(scriptStem, ';'));

Error in SingleRun (line 26)
    run ECM_Easy.m

Error in run (line 112)
evalin('caller', strcat(scriptStem, ';'));

Error in User_Inputs>pushbutton3_Callback (line 272)
run("SingleRun.m")

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in User_Inputs (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)User_Inputs('pushbutton3_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.
```

**Comment by BatParDeveloperTeam** [comment]
Hi Soham,
Thank you for the comment- it really helped us fix the codes!
The issue you spotted was due to an error in reading the current data. As the GUI indicated, the unit of current should be Amp, and it was indeed so in the example data. However, when preprocessing the current data by loadexperiments_.m, the unit of current was taken as mA. I just corrected this issue and updated loadexperiments_.m. Please go have a try with the corrected codes.

Kind regards,
Tao Zhu
